#!/bin/bash

GRID_SIZE=50
VISCOSITY=0.1
DENSITY=1.0

# Initialize velocity field
declare -A u

# Function to update velocity field
update_velocity_field() {
  declare -A laplacian
  for i in $(seq 2 $((GRID_SIZE - 1))); do
    for j in $(seq 2 $((GRID_SIZE - 1))); do
      laplacian[$i,$j]=$((
        ${u[$((i + 1)),$j)]:-0} + ${u[$((i - 1)),$j)]:-0} + ${u[$i,$((j + 1))]:-0} + ${u[$i,$((j - 1))]:-0} - 4 * ${u[$i,$j]:-0}
      ))
    done
  done

  for i in $(seq 1 $GRID_SIZE); do
    for j in $(seq 1 $GRID_SIZE); do
      u[$i,$j]=$(( ${u[$i,$j]:-0} + VISCOSITY * ${laplacian[$i,$j]:-0} / DENSITY ))
    done
  done
}

# Function to hash velocity field
hash_velocity_field() {
  data=""
  for i in $(seq 1 $GRID_SIZE); do
    for j in $(seq 1 $GRID_SIZE); do
      data+=${u[$i,$j]:-0}
    done
  done
  echo -n "$data" | sha256sum | awk '{print $1}'
}

# Run simulation
update_velocity_field

# Output hash
hash=$(hash_velocity_field)
echo "Velocity Field Hash: $hash"
